# Generated by Django 5.2.5 on 2025-08-27 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('size', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=10)),
                ('breed', models.CharField(default='SRD', max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_vet', models.BooleanField(default=False)),
                ('vet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vet_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('castrated', models.BooleanField(default=False)),
                ('in_heat', models.BooleanField(default=False)),
                ('chronic_disease', models.BooleanField(default=False)),
                ('disease_description', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('special_recommendations', models.TextField(blank=True, null=True)),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='api.dog')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='api.owner'),
        ),
    ]
