# Generated by Django 5.2.5 on 2025-10-21 23:39

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='api.owner'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='api.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='api.owner')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='api.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='api.owner')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.servicetype')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='api.stay')),
            ],
            options={
                'ordering': ['-performed_at', '-day', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stay',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['dog', 'check_in'], name='api_stay_dog_id_c530ea_btree'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['check_in'], name='api_stay_check_i_fa4d83_btree'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['dog', 'performed_at'], name='api_service_dog_id_d1283c_btree'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['dog', 'day'], name='api_service_dog_id_d34215_btree'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='api_service_created_6e5ebc_btree'),
        ),
    ]
